ECHO OFF

SET CLASSPATH=src\lib\static\junit\junit-4.12.jar;src\lib\static\junit\hamcrest-core-1.3.jar

SET BUILD_CLASS_DIR_IMPLEMENTATION=bin

SET BUILD_CLASS_DIR_JUNIT=bin

SET BUILD_CLASS_DIR_EXCEPTIONS=bin

SET RUN_CLASSPATH=%BUILD_CLASS_DIR_JUNIT%;%BUILD_CLASS_DIR_IMPLEMENTATION%;%BUILD_CLASS_DIR_EXCEPTIONS%;%CLASSPATH%

SET CLASS_TO_RUN=com.simpleatm.test.SimpleATMTests

ECHO CLASSPATH=%CLASSPATH%
ECHO BUILD_CLASS_DIR_IMPLEMENTATION=%BUILD_CLASS_DIR_IMPLEMENTATION%
ECHO BUILD_CLASS_DIR_JUNIT=%BUILD_CLASS_DIR_JUNIT%
ECHO BUILD_CLASS_DIR_EXCEPTIONS=%BUILD_CLASS_DIR_EXCEPTIONS%
ECHO RUN_CLASSPATH=%RUN_CLASSPATH%
ECHO CLASS_TO_RUN=%CLASS_TO_RUN%

java  -classpath %RUN_CLASSPATH% org.junit.runner.JUnitCore %CLASS_TO_RUN%

PAUSE